{% set name = "pygwalker" %}
{% set version = "0.5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: cb2f11088c7308da03dc21a176a03dd8eb77dc611835deffd24168960e48f6de

build:
  entry_points:
    - pygwalker = bin.pygwalker_command:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >={{ python_min }},<4.0
    - jinja2
    - ipython
    - astor
    - typing_extensions
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb >=0.10.4,<2.0.0
    - pyarrow
    - sqlglot >=23.15.8
    - requests
    - arrow
    - sqlalchemy
    - gw-dsl-parser ==0.1.49.1
    - appdirs
    #- segment-analytics-python ==2.2.3 is called analytics-python
    - analytics-python ==2.2.3
    - pandas
    - pytz
    - kanaries-track ==0.0.5
    - cachetools
    - packaging
    - numpy
    - ipylab <=1.0.0
    #- quickjs is called python-quickjs 1.19.4
    - python-quickjs
    - traitlets
    - anywidget

test:
  imports:
    - pygwalker
  commands:
    - pip check
    - pygwalker --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  description: 'pygwalker: turn your data into an interactive UI for data exploration and visualization'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
    - rxm7706
