{% set name = "pygwalker" %}
{% set version = "0.4.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: 91a7392801e6a5a89687f0205dabecd8042f89dfcfe925cce085bc03f3af0e93

build:
  entry_points:
    - pygwalker = bin.pygwalker_command:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=3.6,<4.0
    - jinja2
    - ipython
    - astor
    - typing-extensions
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb ==0.10.1
    - pyarrow
    - sqlglot >=19.0.0
    - requests
    - arrow
    - sqlalchemy
    # TODO gw-dsl-parser is not available on conda-forge
    # TODO gw-dsl-parser requires wasmtime, which is not available on conda-forge https://github.com/bytecodealliance/wasmtime-py
#    - gw-dsl-parser ==0.1.47
    - appdirs
    # TODO segment-analytics-python is not available on conda-forge
#    - segment-analytics-python ==2.2.3
    - analytics-python ==2.2.2
    - pandas
    - pytz
    # TODO kanaries-track ==0.0.4 is not available on conda-forge
    - kanaries-track ==0.0.3
    - cachetools
    - packaging

test:
  imports:
    - pygwalker
  #commands:
    #- pip check
    #- pygwalker --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
