{% set name = "pygwalker" %}
{% set version = "0.4.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: 747b726e8acd35f20aef8ee74652a948575fb70b5fa8f816a692c9870d0ab0cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=3.6,<4.0
    - ipython
    - jinja2
    - pandas
    - typing_extensions
    - astor
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb >=0.10.0
    - pyarrow
    - sqlglot >=23.15.8
    - requests
    - arrow
    - sqlalchemy
    - analytics-python ==2.2.2
    - appdirs
    - pytz
    - kanaries-track ==0.0.5
    - cachetools
    - packaging
    - numpy <2.0.0
    - ipylab <=1.0.0

test:
  imports:
    - pygwalker
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
