{% set name = "pygwalker" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: b016e3b4106af36c8f5c320d6ad40c29966e321a9f7d6ce72ccba62222cd7f0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=3.6,<4.0
    - ipython
    - jinja2
    - pandas
    - typing_extensions
    - astor
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb
    - pyarrow
    - sqlglot
    - requests
    - arrow
    - sqlalchemy
    - analytics-python
    - appdirs

test:
  imports:
    - pygwalker
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
