{% set name = "pygwalker" %}
{% set version = "0.4.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: 747b726e8acd35f20aef8ee74652a948575fb70b5fa8f816a692c9870d0ab0cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2
  entry_points:
    - pygwalker = bin.pygwalker_command:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }},<4.0
    - jinja2
    - ipython
    - astor
    - typing_extensions
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb >=0.10.1,<2.0.0
    - pyarrow
    - sqlglot >=23.15.8
    - requests
    - arrow
    - sqlalchemy
    # Requires wasmtime (python-wasmtime) for gw-dsl-parser
    #- gw-dsl-parser ==0.1.49.1
    - appdirs
    #- segment-analytics-python ==2.2.3 is called analytics-python
    - analytics-python ==2.2.3
    - pandas
    - pytz
    - kanaries-track ==0.0.5
    - cachetools
    - packaging
    - numpy
    - ipylab <=1.0.0
    #- quickjs is called python-quickjs 1.19.4
    - python-quickjs
    - traitlets
    - anywidget
test:
  imports:
    - pygwalker
  commands:
    #- pip check
    # pygwalker 0.4.9.15 requires gw-dsl-parser, which is not installed.
    - pygwalker --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  description: 'pygwalker: turn your data into an interactive UI for data exploration and visualization'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
    - rxm7706
